"""Product catalog, shipping rate tables, tax rules, and bundle promotions."""

# Product catalog: input_key -> product record
PRODUCTS = {
    "widget-a": {
        "sku": "WIDGET-A",
        "name": "Precision Widget A",
        "price": 29.99,
        "weight_g": 250,
        "category": "electronics",
        "warehouse": "WH-NORTH",
        "fragile": False,
        "dimensions_cm": {"l": 10, "w": 8, "h": 4},
    },
    "widget-b": {
        "sku": "WIDGET-B",
        "name": "Precision Widget B",
        "price": 49.99,
        "weight_g": 350,
        "category": "electronics",
        "warehouse": "WH-NORTH",
        "fragile": False,
        "dimensions_cm": {"l": 12, "w": 10, "h": 5},
    },
    "widget-c": {
        "sku": "WIDGET-C",
        "name": "Precision Widget C",
        "price": 79.99,
        "weight_g": 500,
        "category": "electronics",
        "warehouse": "WH-EAST",
        "fragile": True,
        "dimensions_cm": {"l": 15, "w": 12, "h": 6},
    },
    "cable-1m": {
        "sku": "CABLE-1M",
        "name": "Premium Cable 1m",
        "price": 9.99,
        "weight_g": 100,
        "category": "accessories",
        "warehouse": "WH-NORTH",
        "fragile": False,
        "dimensions_cm": {"l": 20, "w": 5, "h": 2},
    },
    "cable-2m": {
        "sku": "CABLE-2M",
        "name": "Premium Cable 2m",
        "price": 14.99,
        "weight_g": 150,
        "category": "accessories",
        "warehouse": "WH-NORTH",
        "fragile": False,
        "dimensions_cm": {"l": 30, "w": 5, "h": 2},
    },
    "power-supply": {
        "sku": "POWER-SUPPLY",
        "name": "Universal Power Supply",
        "price": 39.99,
        "weight_g": 800,
        "category": "electronics",
        "warehouse": "WH-WEST",
        "fragile": False,
        "dimensions_cm": {"l": 18, "w": 12, "h": 8},
    },
    "mount-wall": {
        "sku": "MOUNT-WALL",
        "name": "Wall Mount Kit",
        "price": 24.99,
        "weight_g": 600,
        "category": "hardware",
        "warehouse": "WH-SOUTH",
        "fragile": False,
        "dimensions_cm": {"l": 25, "w": 20, "h": 5},
    },
    "mount-desk": {
        "sku": "MOUNT-DESK",
        "name": "Desk Mount Kit",
        "price": 19.99,
        "weight_g": 450,
        "category": "hardware",
        "warehouse": "WH-SOUTH",
        "fragile": False,
        "dimensions_cm": {"l": 22, "w": 18, "h": 6},
    },
    "filter-uv": {
        "sku": "FILTER-UV",
        "name": "UV Protective Filter",
        "price": 15.99,
        "weight_g": 80,
        "category": "accessories",
        "warehouse": "WH-EAST",
        "fragile": True,
        "dimensions_cm": {"l": 8, "w": 8, "h": 1},
    },
    "battery-pack": {
        "sku": "BATTERY-PACK",
        "name": "Extended Battery Pack",
        "price": 34.99,
        "weight_g": 400,
        "category": "electronics",
        "warehouse": "WH-NORTH",
        "fragile": False,
        "dimensions_cm": {"l": 14, "w": 9, "h": 3},
    },
    "lens-cap": {
        "sku": "LENS-CAP",
        "name": "Protective Lens Cap",
        "price": 4.99,
        "weight_g": 30,
        "category": "accessories",
        "warehouse": "WH-EAST",
        "fragile": False,
        "dimensions_cm": {"l": 7, "w": 7, "h": 1},
    },
    "cleaning-kit": {
        "sku": "CLEANING-KIT",
        "name": "Sensor Cleaning Kit",
        "price": 19.99,
        "weight_g": 120,
        "category": "accessories",
        "warehouse": "WH-NORTH",
        "fragile": False,
        "dimensions_cm": {"l": 15, "w": 10, "h": 4},
    },
}

# Shipping rate table: zone -> max_weight_g_bracket -> carrier -> rate_usd
# Brackets are upper bounds (inclusive). First bracket that fits is used.
SHIPPING_RATES = {
    "domestic": {
        500: {"standard": 4.99, "express": 9.99, "overnight": 19.99},
        1000: {"standard": 7.99, "express": 14.99, "overnight": 29.99},
        2000: {"standard": 12.99, "express": 24.99, "overnight": 49.99},
        5000: {"standard": 19.99, "express": 39.99, "overnight": 79.99},
        99999: {"standard": 29.99, "express": 59.99, "overnight": 119.99},
    },
    "international": {
        500: {"standard": 12.99, "express": 24.99},
        1000: {"standard": 19.99, "express": 39.99},
        2000: {"standard": 29.99, "express": 59.99},
        5000: {"standard": 44.99, "express": 89.99},
        99999: {"standard": 69.99, "express": 139.99},
    },
}

# Tax rules: state -> category -> tax_rate (0.0 = exempt)
TAX_RULES = {
    "CA": {"electronics": 0.0875, "accessories": 0.0875, "hardware": 0.0875},
    "NY": {"electronics": 0.08, "accessories": 0.08, "hardware": 0.08},
    "TX": {"electronics": 0.0625, "accessories": 0.0625, "hardware": 0.0625},
    "WA": {"electronics": 0.065, "accessories": 0.065, "hardware": 0.065},
    "OR": {"electronics": 0.0, "accessories": 0.0, "hardware": 0.0},
    "MT": {"electronics": 0.0, "accessories": 0.0, "hardware": 0.0},
}

# Bundle promotions: all required_skus must appear in the order to qualify.
BUNDLES = [
    {
        "id": "STARTER-KIT",
        "name": "Starter Kit Bundle",
        "description": "Widget A + Premium Cable 1m + Power Supply — save 15%",
        "required_skus": ["WIDGET-A", "CABLE-1M", "POWER-SUPPLY"],
        "discount_pct": 15.0,
    },
    {
        "id": "PRO-SETUP",
        "name": "Professional Setup Bundle",
        "description": "Widget B + Widget C + Wall Mount — save 20%",
        "required_skus": ["WIDGET-B", "WIDGET-C", "MOUNT-WALL"],
        "discount_pct": 20.0,
    },
    {
        "id": "TRAVEL-BUNDLE",
        "name": "Travel Bundle",
        "description": "Cable 2m + Battery Pack + UV Filter — save 10%",
        "required_skus": ["CABLE-2M", "BATTERY-PACK", "FILTER-UV"],
        "discount_pct": 10.0,
    },
    {
        "id": "PROTECTION-PACK",
        "name": "Protection Pack",
        "description": "Lens Cap + UV Filter + Cleaning Kit — save 12%",
        "required_skus": ["LENS-CAP", "FILTER-UV", "CLEANING-KIT"],
        "discount_pct": 12.0,
    },
]
